### PR TITLE
Fixups because of youtube apiv2 deprecation

### PR DESCRIPTION
**Pull request by droarty**
The youtube api V2 has been deprecated.  This fix switches to a simple url pattern that fetches the thumbnail.

### CODE REVIEW

**Comment by droarty** [comment]
@gnarmis @schultzy51

**Comment by schultzy51** [comment]
I thought we weren't going to use this?

**Comment by gnarmis** [comment]
@schultzy51 this is the fork, it's just the fixes that were already done for this open source component

**Comment by gnarmis** [comment]
Closing because of our "close PRs older than 6 months" adopted rule of thumb at a group code review meeting

**Pull request closed without merging**
